language: java
jdk:
  - openjdk8
service:
  - mysql
dist: trusty
sudo: required
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS xpress;'
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B